spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: kameleoon
    password: kameleoon
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
